export const IS_FETCHING_PAGE = 'IS_FETCHING_PAGE';
export const FETCH_PAGE_BY_ID = 'FETCH_PAGE_BY_ID';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOG_OUT_USER = 'LOG_OUT_USER';
export const LOGOUT = 'LOGOUT';


export const RELOAD_MAP = 'RELOAD_MAP';
export const RELOAD_MAP_FINISH = 'RELOAD_MAP_FINISH';

