export const IS_FETCHING_PAGE = 'IS_FETCHING_PAGE';
export const FETCH_PAGE_BY_ID = 'FETCH_PAGE_BY_ID';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
export const LOG_OUT_USER = 'LOG_OUT_USER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';


export const RELOAD_MAP = 'RELOAD_MAP';
export const RELOAD_MAP_FINISH = 'RELOAD_MAP_FINISH';

